[2025-07-23T08:03:11.558+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-23T08:03:11.576+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: startup_health_score_full_pipeline.extract_raw_text_from_document manual__2025-07-23T08:03:06.237518+00:00 [queued]>
[2025-07-23T08:03:11.582+0000] {taskinstance.py:2631} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: startup_health_score_full_pipeline.extract_raw_text_from_document manual__2025-07-23T08:03:06.237518+00:00 [queued]>
[2025-07-23T08:03:11.582+0000] {taskinstance.py:2884} INFO - Starting attempt 1 of 2
[2025-07-23T08:03:11.592+0000] {taskinstance.py:2907} INFO - Executing <Task(PythonOperator): extract_raw_text_from_document> on 2025-07-23 08:03:06.237518+00:00
[2025-07-23T08:03:11.604+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=90) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-23T08:03:11.605+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2025-07-23T08:03:11.607+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'startup_health_score_full_pipeline', 'extract_raw_text_from_document', 'manual__2025-07-23T08:03:06.237518+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/startup_health_score_dag.py', '--cfg-path', '/tmp/tmp6cctbjws']
[2025-07-23T08:03:11.610+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask extract_raw_text_from_document
[2025-07-23T08:03:11.672+0000] {task_command.py:467} INFO - Running <TaskInstance: startup_health_score_full_pipeline.extract_raw_text_from_document manual__2025-07-23T08:03:06.237518+00:00 [running]> on host e2544795193d
[2025-07-23T08:03:11.744+0000] {taskinstance.py:3157} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='startup_health_score_full_pipeline' AIRFLOW_CTX_TASK_ID='extract_raw_text_from_document' AIRFLOW_CTX_EXECUTION_DATE='2025-07-23T08:03:06.237518+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-23T08:03:06.237518+00:00'
[2025-07-23T08:03:11.745+0000] {taskinstance.py:740} INFO - ::endgroup::
[2025-07-23T08:03:11.764+0000] {log.py:232} WARNING - 2025-07-23 08:03:11,764 - startup_health_score - INFO - Extracting raw text from /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf...
[2025-07-23T08:03:11.764+0000] {startup_health_score_dag.py:84} INFO - Extracting raw text from /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf...
[2025-07-23T08:03:11.793+0000] {log.py:232} WARNING - 2025-07-23 08:03:11,793 - startup_health_score - INFO - Tesseract OCR engine found (version: 5.3.0).
[2025-07-23T08:03:11.793+0000] {kpi_extractor.py:49} INFO - Tesseract OCR engine found (version: 5.3.0).
[2025-07-23T08:03:11.794+0000] {log.py:232} WARNING - 2025-07-23 08:03:11,793 - startup_health_score - INFO - KPIExtractor initialized.
[2025-07-23T08:03:11.793+0000] {kpi_extractor.py:53} INFO - KPIExtractor initialized.
[2025-07-23T08:03:11.794+0000] {log.py:232} WARNING - 2025-07-23 08:03:11,794 - startup_health_score - INFO - Attempting to extract raw text from: /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf (Type: .pdf)
[2025-07-23T08:03:11.794+0000] {kpi_extractor.py:130} INFO - Attempting to extract raw text from: /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf (Type: .pdf)
[2025-07-23T08:03:12.227+0000] {log.py:232} WARNING - 2025-07-23 08:03:12,227 - startup_health_score - INFO - Successfully extracted text directly from PDF: /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf
[2025-07-23T08:03:12.227+0000] {kpi_extractor.py:104} INFO - Successfully extracted text directly from PDF: /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf
[2025-07-23T08:03:12.228+0000] {log.py:232} WARNING - 2025-07-23 08:03:12,228 - startup_health_score - INFO - Successfully extracted raw text from /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf.
[2025-07-23T08:03:12.228+0000] {kpi_extractor.py:155} INFO - Successfully extracted raw text from /opt/***/uploads/ConnectIn - Monthly Investor Update_ June 2025.pdf.
[2025-07-23T08:03:12.283+0000] {log.py:232} WARNING - 2025-07-23 08:03:12,283 - startup_health_score - ERROR - Failed to write extracted text to file /opt/***/processed_data/extracted_text.txt: [Errno 1] Operation not permitted: '/opt/***/processed_data/extracted_text.txt'
[2025-07-23T08:03:12.283+0000] {startup_health_score_dag.py:95} ERROR - Failed to write extracted text to file /opt/***/processed_data/extracted_text.txt: [Errno 1] Operation not permitted: '/opt/***/processed_data/extracted_text.txt'
[2025-07-23T08:03:12.296+0000] {taskinstance.py:3336} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/startup_health_score_dag.py", line 90, in _extract_raw_text
    with open(EXTRACTED_TEXT_FILE, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/opt/airflow/processed_data/extracted_text.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/startup_health_score_dag.py", line 96, in _extract_raw_text
    raise AirflowException(f"Failed to write extracted text: {e}")
airflow.exceptions.AirflowException: Failed to write extracted text: [Errno 1] Operation not permitted: '/opt/***/processed_data/extracted_text.txt'
[2025-07-23T08:03:12.341+0000] {taskinstance.py:1242} INFO - Marking task as UP_FOR_RETRY. dag_id=startup_health_score_full_pipeline, task_id=extract_raw_text_from_document, run_id=manual__2025-07-23T08:03:06.237518+00:00, execution_date=20250723T080306, start_date=20250723T080311, end_date=20250723T080312
[2025-07-23T08:03:12.363+0000] {taskinstance.py:349} INFO - ::group::Post task execution logs
[2025-07-23T08:03:12.364+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task extract_raw_text_from_document (Failed to write extracted text: [Errno 1] Operation not permitted: '/opt/***/processed_data/extracted_text.txt'; 92)
Traceback (most recent call last):
  File "/opt/airflow/dags/startup_health_score_dag.py", line 90, in _extract_raw_text
    with open(EXTRACTED_TEXT_FILE, 'w', encoding='utf-8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted: '/opt/airflow/processed_data/extracted_text.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3029, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 282, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3184, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3208, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 776, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 742, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/startup_health_score_dag.py", line 96, in _extract_raw_text
    raise AirflowException(f"Failed to write extracted text: {e}")
airflow.exceptions.AirflowException: Failed to write extracted text: [Errno 1] Operation not permitted: '/opt/***/processed_data/extracted_text.txt'
[2025-07-23T08:03:12.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-23T08:03:12.398+0000] {taskinstance.py:3924} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-23T08:03:12.399+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
